--liquibase formatted sql
--changeset PratikL:g789012345-0123-4567-89ab-cdef01234567  runOnChange:true


CREATE OR REPLACE VIEW HRDATA.V_ATTENDANCE_SUMMARY AS
SELECT
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NUMBER,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS EMPLOYEE_NAME,
    D.DEPARTMENT_NAME,
    COUNT(CASE WHEN A.STATUS = 'PRESENT' THEN 1 END) AS DAYS_PRESENT,
    COUNT(CASE WHEN A.STATUS = 'SICK_LEAVE' THEN 1 END) AS DAYS_SICK,
    COUNT(CASE WHEN A.STATUS = 'VACATION' THEN 1 END) AS DAYS_VACATION,
    COUNT(CASE WHEN A.STATUS = 'HALF_DAY' THEN 1 END) AS DAYS_HALF,
    SUM(COALESCE(A.HOURS_WORKED, 0)) AS TOTAL_HOURS_WORKED,
    AVG(COALESCE(A.HOURS_WORKED, 0)) AS AVG_HOURS_PER_DAY
FROM HRDB.EMPLOYEES E
LEFT JOIN HRDB.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HRDB.ATTENDANCE A ON E.EMPLOYEE_ID = A.EMPLOYEE_ID
WHERE E.IS_ACTIVE = TRUE
GROUP BY
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NUMBER,
    E.FIRST_NAME,
    E.LAST_NAME,
    D.DEPARTMENT_NAME;
