--liquibase formatted sql
--changeset RAML:f678901234-f012-3456-789a-bcdef0123456  runOnChange:true


CREATE OR REPLACE VIEW HRDATA.V_EMPLOYEE_DIRECTORY AS
SELECT
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NUMBER,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS FULL_NAME,
    E.EMAIL,
    E.PHONE_NUMBER,
    E.JOB_TITLE,
    D.DEPARTMENT_NAME,
    D.DEPARTMENT_CODE,
    E.LOCATION,
    M.FIRST_NAME || ' ' || M.LAST_NAME AS MANAGER_NAME,
    E.EMPLOYMENT_STATUS,
    E.EMPLOYMENT_TYPE,
    E.HIRE_DATE,
    DATEDIFF(YEAR, E.HIRE_DATE, CURRENT_DATE()) AS YEARS_OF_SERVICE
FROM HRDB.EMPLOYEES E
LEFT JOIN HRDB.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN HRDB.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
WHERE E.IS_ACTIVE = TRUE;
