--liquibase formatted sql
--changeset PratikL:ak789012345-ef01-2345-6789-678901234567  runOnChange:true


CREATE OR REPLACE VIEW INSURANCEDATA.V_CLAIMS_STATUS AS
SELECT
    C.CLAIM_ID,
    C.CLAIM_NUMBER,
    C.CLAIM_TYPE,
    C.CLAIM_STATUS,
    C.CLAIM_DATE,
    C.INCIDENT_DATE,
    P.POLICY_NUMBER,
    P.POLICY_TYPE,
    PH.FIRST_NAME || ' ' || PH.LAST_NAME AS POLICYHOLDER_NAME,
    C.CLAIMED_AMOUNT,
    C.APPROVED_AMOUNT,
    C.PAID_AMOUNT,
    C.DEDUCTIBLE_APPLIED,
    DATEDIFF(DAY, C.CLAIM_DATE, COALESCE(C.RESOLUTION_DATE, CURRENT_DATE())) AS DAYS_TO_RESOLVE,
    COUNT(CD.DOCUMENT_ID) AS DOCUMENTS_SUBMITTED,
    SUM(CASE WHEN CD.VERIFIED = TRUE THEN 1 ELSE 0 END) AS DOCUMENTS_VERIFIED
FROM INSURANCEDB.CLAIMS C
INNER JOIN INSURANCEDB.POLICIES P ON C.POLICY_ID = P.POLICY_ID
INNER JOIN INSURANCEDB.POLICYHOLDERS PH ON P.POLICYHOLDER_ID = PH.POLICYHOLDER_ID
LEFT JOIN INSURANCEDB.CLAIM_DOCUMENTS CD ON C.CLAIM_ID = CD.CLAIM_ID
GROUP BY
    C.CLAIM_ID, C.CLAIM_NUMBER, C.CLAIM_TYPE, C.CLAIM_STATUS,
    C.CLAIM_DATE, C.INCIDENT_DATE, P.POLICY_NUMBER, P.POLICY_TYPE,
    PH.FIRST_NAME, PH.LAST_NAME, C.CLAIMED_AMOUNT, C.APPROVED_AMOUNT,
    C.PAID_AMOUNT, C.DEDUCTIBLE_APPLIED, C.RESOLUTION_DATE;
