--liquibase formatted sql
--changeset RAML:aj678901234-def0-1234-5678-567890123456  runOnChange:true


CREATE OR REPLACE VIEW INSURANCEDATA.V_POLICY_OVERVIEW AS
SELECT
    P.POLICY_ID,
    P.POLICY_NUMBER,
    P.POLICY_TYPE,
    P.COVERAGE_TYPE,
    PH.FIRST_NAME || ' ' || PH.LAST_NAME AS POLICYHOLDER_NAME,
    PH.EMAIL AS POLICYHOLDER_EMAIL,
    PH.PHONE_NUMBER AS POLICYHOLDER_PHONE,
    P.START_DATE,
    P.END_DATE,
    P.STATUS,
    P.PREMIUM_AMOUNT,
    P.PAYMENT_FREQUENCY,
    P.COVERAGE_LIMIT,
    P.DEDUCTIBLE,
    COUNT(C.CLAIM_ID) AS TOTAL_CLAIMS,
    SUM(CASE WHEN C.CLAIM_STATUS = 'PAID' THEN C.PAID_AMOUNT ELSE 0 END) AS TOTAL_PAID_CLAIMS,
    DATEDIFF(DAY, CURRENT_DATE(), P.END_DATE) AS DAYS_UNTIL_EXPIRATION,
    CASE
        WHEN DATEDIFF(DAY, CURRENT_DATE(), P.END_DATE) < 30 THEN 'EXPIRING_SOON'
        WHEN DATEDIFF(DAY, CURRENT_DATE(), P.END_DATE) < 0 THEN 'EXPIRED'
        ELSE 'ACTIVE'
    END AS RENEWAL_STATUS
FROM INSURANCEDB.POLICIES P
INNER JOIN INSURANCEDB.POLICYHOLDERS PH ON P.POLICYHOLDER_ID = PH.POLICYHOLDER_ID
LEFT JOIN INSURANCEDB.CLAIMS C ON P.POLICY_ID = C.POLICY_ID
GROUP BY
    P.POLICY_ID, P.POLICY_NUMBER, P.POLICY_TYPE, P.COVERAGE_TYPE,
    PH.FIRST_NAME, PH.LAST_NAME, PH.EMAIL, PH.PHONE_NUMBER,
    P.START_DATE, P.END_DATE, P.STATUS, P.PREMIUM_AMOUNT,
    P.PAYMENT_FREQUENCY, P.COVERAGE_LIMIT, P.DEDUCTIBLE;
