--liquibase formatted sql
--changeset RAML:ag345678901-abcd-ef01-2345-234567890123  runOnChange:true


CREATE OR REPLACE PROCEDURE TELECOMDB.SP_CHANGE_SERVICE_PLAN(
    SUBSCRIBER_ID_PARAM VARCHAR,
    NEW_PLAN_ID_PARAM VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    OLD_PLAN_ID VARCHAR;
    OLD_PLAN_NAME VARCHAR;
    NEW_PLAN_NAME VARCHAR;
    NEW_MONTHLY_FEE DECIMAL(10,2);
    RESULT_MSG VARCHAR;
BEGIN
    -- Get current plan
    SELECT PLAN_ID INTO OLD_PLAN_ID
    FROM TELECOMDB.SUBSCRIBERS
    WHERE SUBSCRIBER_ID = :SUBSCRIBER_ID_PARAM;

    IF (OLD_PLAN_ID IS NULL) THEN
        RETURN 'ERROR: Subscriber not found: ' || :SUBSCRIBER_ID_PARAM;
    END IF;

    -- Get old plan name
    SELECT PLAN_NAME INTO OLD_PLAN_NAME
    FROM TELECOMDB.SERVICE_PLANS
    WHERE PLAN_ID = :OLD_PLAN_ID;

    -- Get new plan details
    SELECT PLAN_NAME, MONTHLY_FEE INTO NEW_PLAN_NAME, NEW_MONTHLY_FEE
    FROM TELECOMDB.SERVICE_PLANS
    WHERE PLAN_ID = :NEW_PLAN_ID_PARAM;

    IF (NEW_PLAN_NAME IS NULL) THEN
        RETURN 'ERROR: Plan not found: ' || :NEW_PLAN_ID_PARAM;
    END IF;

    -- Update subscriber plan
    UPDATE TELECOMDB.SUBSCRIBERS
    SET PLAN_ID = :NEW_PLAN_ID_PARAM
    WHERE SUBSCRIBER_ID = :SUBSCRIBER_ID_PARAM;

    RESULT_MSG := 'Plan changed for subscriber ' || :SUBSCRIBER_ID_PARAM ||
                  ' from "' || :OLD_PLAN_NAME || '" to "' || :NEW_PLAN_NAME || '"' ||
                  '. New monthly fee: $' || :NEW_MONTHLY_FEE;

    RETURN RESULT_MSG;
END;
$$;
