--liquibase formatted sql
--changeset PratikL:af234567890-9abc-def0-1234-123456789012  runOnChange:true


CREATE OR REPLACE VIEW TELECOMDATA.V_NETWORK_COVERAGE AS
SELECT
    T.TOWER_ID,
    T.TOWER_NAME,
    T.CITY,
    T.STATE,
    T.TECHNOLOGY,
    T.BAND_FREQUENCY,
    T.COVERAGE_RADIUS_KM,
    T.CAPACITY,
    T.STATUS,
    COUNT(DISTINCT S.SUBSCRIBER_ID) AS SUBSCRIBERS_IN_AREA,
    ROUND((COUNT(DISTINCT S.SUBSCRIBER_ID)::DECIMAL / T.CAPACITY) * 100, 2) AS CAPACITY_UTILIZATION_PCT
FROM TELECOMDB.TOWER_LOCATIONS T
LEFT JOIN TELECOMDB.SUBSCRIBERS S ON T.CITY = S.CITY AND S.STATUS = 'ACTIVE'
GROUP BY
    T.TOWER_ID, T.TOWER_NAME, T.CITY, T.STATE, T.TECHNOLOGY,
    T.BAND_FREQUENCY, T.COVERAGE_RADIUS_KM, T.CAPACITY, T.STATUS;
