--liquibase formatted sql
--changeset RAML:ae123456789-89ab-cdef-0123-012345678901  runOnChange:true


CREATE OR REPLACE VIEW TELECOMDATA.V_SUBSCRIBER_SUMMARY AS
SELECT
    S.SUBSCRIBER_ID,
    S.ACCOUNT_NUMBER,
    S.FIRST_NAME || ' ' || S.LAST_NAME AS SUBSCRIBER_NAME,
    S.PHONE_NUMBER,
    S.EMAIL,
    S.STATUS,
    S.ACTIVATION_DATE,
    DATEDIFF(MONTH, S.ACTIVATION_DATE, CURRENT_DATE()) AS MONTHS_SUBSCRIBED,
    SP.PLAN_NAME,
    SP.MONTHLY_FEE,
    S.AUTO_PAY_ENABLED,
    S.PAPERLESS_BILLING,
    AVG(U.DATA_USED_MB) AS AVG_DAILY_DATA_MB,
    AVG(U.VOICE_MINUTES) AS AVG_DAILY_MINUTES,
    SUM(U.TOTAL_CHARGES) AS TOTAL_CHARGES_LAST_30_DAYS
FROM TELECOMDB.SUBSCRIBERS S
LEFT JOIN TELECOMDB.SERVICE_PLANS SP ON S.PLAN_ID = SP.PLAN_ID
LEFT JOIN TELECOMDB.USAGE_RECORDS U ON S.SUBSCRIBER_ID = U.SUBSCRIBER_ID
    AND U.USAGE_DATE >= DATEADD(DAY, -30, CURRENT_DATE())
GROUP BY
    S.SUBSCRIBER_ID, S.ACCOUNT_NUMBER, S.FIRST_NAME, S.LAST_NAME,
    S.PHONE_NUMBER, S.EMAIL, S.STATUS, S.ACTIVATION_DATE,
    SP.PLAN_NAME, SP.MONTHLY_FEE, S.AUTO_PAY_ENABLED, S.PAPERLESS_BILLING;
