--liquibase formatted sql
--changeset RAML:5c6d7e8f-9012-3456-7890-abcdef012345  runOnChange:true


CREATE OR REPLACE VIEW FINANCEDATA.V_ACCOUNT_SUMMARY AS
SELECT
    CA.ACCOUNT_ID,
    CA.ACCOUNT_NUMBER,
    CA.ACCOUNT_TYPE,
    CI.FIRST_NAME,
    CI.LAST_NAME,
    CI.EMAIL,
    CA.CURRENCY_CODE,
    CA.CURRENT_BALANCE,
    CA.AVAILABLE_BALANCE,
    CA.STATUS,
    CA.RELATIONSHIP_MANAGER,
    CI.CUSTOMER_SEGMENT,
    CI.RISK_RATING,
    COUNT(T.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(CASE WHEN T.TRANSACTION_TYPE = 'DEPOSIT' THEN T.AMOUNT ELSE 0 END) AS TOTAL_DEPOSITS,
    SUM(CASE WHEN T.TRANSACTION_TYPE IN ('WITHDRAWAL', 'PURCHASE') THEN ABS(T.AMOUNT) ELSE 0 END) AS TOTAL_WITHDRAWALS,
    CA.LAST_TRANSACTION_DATE
FROM FINANCEDB.CUSTOMER_ACCOUNTS CA
INNER JOIN FINANCEDB.CUSTOMER_INFO CI ON CA.CUSTOMER_ID = CI.CUSTOMER_ID
LEFT JOIN FINANCEDB.TRANSACTIONS T ON CA.ACCOUNT_ID = T.ACCOUNT_ID
WHERE CA.STATUS = 'ACTIVE'
GROUP BY
    CA.ACCOUNT_ID,
    CA.ACCOUNT_NUMBER,
    CA.ACCOUNT_TYPE,
    CI.FIRST_NAME,
    CI.LAST_NAME,
    CI.EMAIL,
    CA.CURRENCY_CODE,
    CA.CURRENT_BALANCE,
    CA.AVAILABLE_BALANCE,
    CA.STATUS,
    CA.RELATIONSHIP_MANAGER,
    CI.CUSTOMER_SEGMENT,
    CI.RISK_RATING,
    CA.LAST_TRANSACTION_DATE;
