--liquibase formatted sql
--changeset PratikL:6d7e8f90-1234-5678-9abc-def012345678  runOnChange:true


CREATE OR REPLACE VIEW FINANCEDATA.V_TRANSACTION_HISTORY AS
SELECT
    T.TRANSACTION_ID,
    T.ACCOUNT_ID,
    CA.ACCOUNT_NUMBER,
    CA.ACCOUNT_TYPE,
    CI.FIRST_NAME || ' ' || CI.LAST_NAME AS CUSTOMER_NAME,
    T.TRANSACTION_TYPE,
    T.TRANSACTION_DATE,
    T.AMOUNT,
    T.CURRENCY_CODE,
    T.DESCRIPTION,
    T.MERCHANT_NAME,
    T.MERCHANT_CATEGORY,
    T.STATUS,
    T.CHANNEL,
    T.BALANCE_AFTER_TRANSACTION,
    TL.SINGLE_TRANSACTION_LIMIT,
    CASE
        WHEN ABS(T.AMOUNT) > TL.SINGLE_TRANSACTION_LIMIT THEN 'OVER_LIMIT'
        WHEN ABS(T.AMOUNT) > (TL.SINGLE_TRANSACTION_LIMIT * 0.8) THEN 'NEAR_LIMIT'
        ELSE 'WITHIN_LIMIT'
    END AS LIMIT_STATUS
FROM FINANCEDB.TRANSACTIONS T
INNER JOIN FINANCEDB.CUSTOMER_ACCOUNTS CA ON T.ACCOUNT_ID = CA.ACCOUNT_ID
INNER JOIN FINANCEDB.CUSTOMER_INFO CI ON CA.CUSTOMER_ID = CI.CUSTOMER_ID
LEFT JOIN FINANCEDB.TRANSACTION_LIMITS TL ON CA.ACCOUNT_TYPE = TL.ACCOUNT_TYPE
WHERE T.STATUS = 'COMPLETED'
ORDER BY T.TRANSACTION_DATE DESC;
