--liquibase formatted sql
--changeset RAML:al890123456-f012-3456-789a-789012345678  runOnChange:true


CREATE OR REPLACE PROCEDURE INSURANCEDB.SP_PROCESS_CLAIM_PAYMENT(
    CLAIM_ID_PARAM VARCHAR,
    PAYMENT_AMOUNT DECIMAL(12,2),
    RESOLUTION_NOTES_PARAM VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    CLAIM_NUMBER_VAR VARCHAR;
    APPROVED_AMOUNT_VAR DECIMAL(12,2);
    CURRENT_STATUS VARCHAR;
    RESULT_MSG VARCHAR;
BEGIN
    -- Get claim details
    SELECT CLAIM_NUMBER, APPROVED_AMOUNT, CLAIM_STATUS
    INTO CLAIM_NUMBER_VAR, APPROVED_AMOUNT_VAR, CURRENT_STATUS
    FROM INSURANCEDB.CLAIMS
    WHERE CLAIM_ID = :CLAIM_ID_PARAM;

    IF (CLAIM_NUMBER_VAR IS NULL) THEN
        RETURN 'ERROR: Claim not found: ' || :CLAIM_ID_PARAM;
    END IF;

    IF (CURRENT_STATUS NOT IN ('APPROVED', 'IN_REVIEW')) THEN
        RETURN 'ERROR: Claim cannot be paid. Current status: ' || :CURRENT_STATUS;
    END IF;

    IF (PAYMENT_AMOUNT > APPROVED_AMOUNT_VAR) THEN
        RETURN 'ERROR: Payment amount (' || :PAYMENT_AMOUNT || ') exceeds approved amount (' || :APPROVED_AMOUNT_VAR || ')';
    END IF;

    -- Update claim with payment
    UPDATE INSURANCEDB.CLAIMS
    SET PAID_AMOUNT = :PAYMENT_AMOUNT,
        CLAIM_STATUS = 'PAID',
        RESOLUTION_DATE = CURRENT_DATE(),
        RESOLUTION_NOTES = :RESOLUTION_NOTES_PARAM
    WHERE CLAIM_ID = :CLAIM_ID_PARAM;

    RESULT_MSG := 'Payment processed for claim ' || :CLAIM_NUMBER_VAR ||
                  '. Amount: $' || :PAYMENT_AMOUNT ||
                  '. Status updated to PAID.';

    RETURN RESULT_MSG;
END;
$$;
