--liquibase formatted sql
--changeset PratikL:aa789012345-4567-89ab-cdef-678901234567  runOnChange:true


CREATE OR REPLACE VIEW REALESTATEDATA.V_AGENT_PERFORMANCE AS
SELECT
    A.AGENT_ID,
    A.FIRST_NAME || ' ' || A.LAST_NAME AS AGENT_NAME,
    A.OFFICE_LOCATION,
    A.SPECIALIZATION,
    A.YEARS_EXPERIENCE,
    COUNT(DISTINCT P.PROPERTY_ID) AS ACTIVE_LISTINGS,
    COUNT(DISTINCT S.SHOWING_ID) AS TOTAL_SHOWINGS,
    AVG(CASE WHEN S.INTEREST_LEVEL = 'VERY_HIGH' THEN 5
             WHEN S.INTEREST_LEVEL = 'HIGH' THEN 4
             WHEN S.INTEREST_LEVEL = 'MEDIUM' THEN 3
             WHEN S.INTEREST_LEVEL = 'LOW' THEN 2
             ELSE 1 END) AS AVG_INTEREST_SCORE,
    COUNT(DISTINCT O.OFFER_ID) AS TOTAL_OFFERS,
    SUM(CASE WHEN P.STATUS = 'SOLD' THEN 1 ELSE 0 END) AS PROPERTIES_SOLD_YTD,
    SUM(CASE WHEN P.STATUS = 'SOLD' THEN P.SOLD_PRICE ELSE 0 END) AS SALES_VOLUME_YTD
FROM REALESTATEDB.AGENTS A
LEFT JOIN REALESTATEDB.PROPERTIES P ON A.AGENT_ID = P.AGENT_ID
LEFT JOIN REALESTATEDB.SHOWINGS S ON P.PROPERTY_ID = S.PROPERTY_ID AND S.STATUS = 'COMPLETED'
LEFT JOIN REALESTATEDB.OFFERS O ON P.PROPERTY_ID = O.PROPERTY_ID
GROUP BY
    A.AGENT_ID, A.FIRST_NAME, A.LAST_NAME, A.OFFICE_LOCATION,
    A.SPECIALIZATION, A.YEARS_EXPERIENCE;
