--liquibase formatted sql
--changeset RAML:z678901234-3456-789a-bcde-567890123456  runOnChange:true


CREATE OR REPLACE VIEW REALESTATEDATA.V_PROPERTY_LISTINGS AS
SELECT
    P.PROPERTY_ID,
    P.LISTING_ID,
    P.PROPERTY_TYPE,
    P.ADDRESS,
    P.CITY,
    P.STATE,
    P.BEDROOMS,
    P.BATHROOMS,
    P.SQUARE_FEET,
    P.LISTING_PRICE,
    P.STATUS,
    P.LISTING_DATE,
    DATEDIFF(DAY, P.LISTING_DATE, CURRENT_DATE()) AS DAYS_ON_MARKET,
    A.FIRST_NAME || ' ' || A.LAST_NAME AS AGENT_NAME,
    A.PHONE_NUMBER AS AGENT_PHONE,
    A.EMAIL AS AGENT_EMAIL,
    COUNT(DISTINCT S.SHOWING_ID) AS TOTAL_SHOWINGS,
    COUNT(DISTINCT O.OFFER_ID) AS TOTAL_OFFERS,
    MAX(O.OFFER_AMOUNT) AS HIGHEST_OFFER
FROM REALESTATEDB.PROPERTIES P
LEFT JOIN REALESTATEDB.AGENTS A ON P.AGENT_ID = A.AGENT_ID
LEFT JOIN REALESTATEDB.SHOWINGS S ON P.PROPERTY_ID = S.PROPERTY_ID
LEFT JOIN REALESTATEDB.OFFERS O ON P.PROPERTY_ID = O.PROPERTY_ID
WHERE P.STATUS IN ('ACTIVE', 'UNDER_CONTRACT')
GROUP BY
    P.PROPERTY_ID, P.LISTING_ID, P.PROPERTY_TYPE, P.ADDRESS,
    P.CITY, P.STATE, P.BEDROOMS, P.BATHROOMS, P.SQUARE_FEET,
    P.LISTING_PRICE, P.STATUS, P.LISTING_DATE,
    A.FIRST_NAME, A.LAST_NAME, A.PHONE_NUMBER, A.EMAIL;
