--liquibase formatted sql
--changeset PratikL:l234567890-5678-9abc-def0-123456789012  runOnChange:true


CREATE OR REPLACE VIEW MFGDATA.V_MATERIAL_INVENTORY AS
SELECT
    RM.MATERIAL_ID,
    RM.MATERIAL_CODE,
    RM.MATERIAL_NAME,
    RM.CATEGORY,
    RM.QUANTITY_IN_STOCK,
    RM.REORDER_POINT,
    RM.UNIT_OF_MEASURE,
    RM.UNIT_COST,
    (RM.QUANTITY_IN_STOCK * RM.UNIT_COST) AS TOTAL_VALUE,
    RM.STORAGE_LOCATION,
    CASE
        WHEN RM.QUANTITY_IN_STOCK = 0 THEN 'OUT_OF_STOCK'
        WHEN RM.QUANTITY_IN_STOCK <= RM.REORDER_POINT THEN 'REORDER_NEEDED'
        WHEN RM.QUANTITY_IN_STOCK <= (RM.REORDER_POINT * 1.5) THEN 'LOW_STOCK'
        ELSE 'ADEQUATE'
    END AS STOCK_STATUS,
    RM.LAST_PURCHASE_DATE,
    DATEDIFF(DAY, RM.LAST_PURCHASE_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_PURCHASE
FROM MFGDB.RAW_MATERIALS RM;
