--liquibase formatted sql
--changeset RAML:k123456789-4567-89ab-cdef-012345678901  runOnChange:true


CREATE OR REPLACE VIEW MFGDATA.V_PRODUCTION_STATUS AS
SELECT
    PO.ORDER_ID,
    PO.ORDER_NUMBER,
    PO.PRODUCT_CODE,
    PO.PRODUCT_NAME,
    PO.QUANTITY_ORDERED,
    PO.QUANTITY_PRODUCED,
    ROUND((PO.QUANTITY_PRODUCED::DECIMAL / NULLIF(PO.QUANTITY_ORDERED, 0)) * 100, 2) AS COMPLETION_PERCENTAGE,
    PO.PRODUCTION_LINE,
    PO.STATUS,
    PO.PRIORITY,
    PO.START_DATE,
    PO.END_DATE,
    PO.ESTIMATED_COST,
    PO.ACTUAL_COST,
    COALESCE(PO.ACTUAL_COST - PO.ESTIMATED_COST, 0) AS COST_VARIANCE,
    QI.OVERALL_STATUS AS QC_STATUS,
    QI.PASS_RATE AS QC_PASS_RATE
FROM MFGDB.PRODUCTION_ORDERS PO
LEFT JOIN (
    SELECT PRODUCTION_ORDER_ID, OVERALL_STATUS, PASS_RATE
    FROM MFGDB.QUALITY_INSPECTIONS
    WHERE INSPECTION_TYPE = 'FINAL_INSPECTION'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCTION_ORDER_ID ORDER BY INSPECTION_DATE DESC) = 1
) QI ON PO.ORDER_ID = QI.PRODUCTION_ORDER_ID;
