--liquibase formatted sql
--changeset RAML:7e8f9012-3456-7890-abcd-ef0123456789  runOnChange:true


CREATE OR REPLACE PROCEDURE FINANCEDB.SP_CALCULATE_ACCOUNT_BALANCE(ACCOUNT_ID_PARAM VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    OPENING_BALANCE DECIMAL(18,2);
    TOTAL_CREDITS DECIMAL(18,2);
    TOTAL_DEBITS DECIMAL(18,2);
    CALCULATED_BALANCE DECIMAL(18,2);
    RESULT_MESSAGE VARCHAR;
BEGIN
    -- Get opening balance
    SELECT CURRENT_BALANCE INTO OPENING_BALANCE
    FROM FINANCEDB.CUSTOMER_ACCOUNTS
    WHERE ACCOUNT_ID = :ACCOUNT_ID_PARAM;

    -- Calculate total credits
    SELECT COALESCE(SUM(AMOUNT), 0) INTO TOTAL_CREDITS
    FROM FINANCEDB.TRANSACTIONS
    WHERE ACCOUNT_ID = :ACCOUNT_ID_PARAM
    AND AMOUNT > 0
    AND STATUS = 'COMPLETED';

    -- Calculate total debits
    SELECT COALESCE(SUM(ABS(AMOUNT)), 0) INTO TOTAL_DEBITS
    FROM FINANCEDB.TRANSACTIONS
    WHERE ACCOUNT_ID = :ACCOUNT_ID_PARAM
    AND AMOUNT < 0
    AND STATUS = 'COMPLETED';

    -- Calculate final balance
    CALCULATED_BALANCE := OPENING_BALANCE;

    -- Update account balance
    UPDATE FINANCEDB.CUSTOMER_ACCOUNTS
    SET CURRENT_BALANCE = :CALCULATED_BALANCE,
        MODIFIED_DATETIME = CURRENT_TIMESTAMP()
    WHERE ACCOUNT_ID = :ACCOUNT_ID_PARAM;

    RESULT_MESSAGE := 'Balance calculated for account ' || :ACCOUNT_ID_PARAM ||
                      '. Opening: ' || :OPENING_BALANCE ||
                      ', Credits: ' || :TOTAL_CREDITS ||
                      ', Debits: ' || :TOTAL_DEBITS ||
                      ', Final: ' || :CALCULATED_BALANCE;

    RETURN RESULT_MESSAGE;
END;
$$;
