--liquibase formatted sql
--changeset RAML:r890123456-bcde-f012-3456-789012345678  runOnChange:true


CREATE OR REPLACE PROCEDURE EDUDB.SP_CALCULATE_GPA(STUDENT_ID_PARAM VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    TOTAL_GRADE_POINTS DECIMAL(10,2);
    TOTAL_CREDITS INT;
    CALCULATED_GPA DECIMAL(3,2);
    RESULT_MSG VARCHAR;
BEGIN
    -- Calculate total grade points weighted by credits
    SELECT
        SUM(E.GRADE_POINTS * C.CREDITS),
        SUM(C.CREDITS)
    INTO TOTAL_GRADE_POINTS, TOTAL_CREDITS
    FROM EDUDB.ENROLLMENTS E
    INNER JOIN EDUDB.COURSES C ON E.COURSE_ID = C.COURSE_ID
    WHERE E.STUDENT_ID = :STUDENT_ID_PARAM
    AND E.STATUS = 'COMPLETED'
    AND E.GRADE_POINTS IS NOT NULL;

    -- Calculate GPA
    IF (TOTAL_CREDITS > 0) THEN
        CALCULATED_GPA := ROUND(:TOTAL_GRADE_POINTS / :TOTAL_CREDITS, 2);
    ELSE
        CALCULATED_GPA := 0.00;
    END IF;

    -- Update student record
    UPDATE EDUDB.STUDENTS
    SET GPA = :CALCULATED_GPA,
        TOTAL_CREDITS_EARNED = :TOTAL_CREDITS
    WHERE STUDENT_ID = :STUDENT_ID_PARAM;

    RESULT_MSG := 'GPA calculated for student ' || :STUDENT_ID_PARAM ||
                  '. Total Credits: ' || :TOTAL_CREDITS ||
                  ', GPA: ' || :CALCULATED_GPA;

    RETURN RESULT_MSG;
END;
$$;
