--liquibase formatted sql
--changeset PratikL:b234567890-bcde-f012-3456-789abcdef012  runOnChange:true


CREATE OR REPLACE VIEW RETAILDATA.V_INVENTORY_STATUS AS
SELECT
    P.PRODUCT_ID,
    P.SKU,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    P.STOCK_QUANTITY,
    P.REORDER_LEVEL,
    P.UNIT_PRICE,
    P.COST_PRICE,
    (P.UNIT_PRICE - P.COST_PRICE) AS PROFIT_MARGIN,
    S.SUPPLIER_NAME,
    S.CONTACT_PERSON,
    S.RATING AS SUPPLIER_RATING,
    CASE
        WHEN P.STOCK_QUANTITY = 0 THEN 'OUT_OF_STOCK'
        WHEN P.STOCK_QUANTITY <= P.REORDER_LEVEL THEN 'LOW_STOCK'
        WHEN P.STOCK_QUANTITY <= (P.REORDER_LEVEL * 2) THEN 'MODERATE_STOCK'
        ELSE 'ADEQUATE_STOCK'
    END AS INVENTORY_STATUS,
    P.IS_ACTIVE
FROM RETAILDB.PRODUCTS P
LEFT JOIN RETAILDB.SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID
WHERE P.IS_ACTIVE = TRUE;
