--liquibase formatted sql
--changeset RAML:a123456789-abcd-ef01-2345-6789abcdef01  runOnChange:true


CREATE OR REPLACE VIEW RETAILDATA.V_ORDER_DETAILS AS
SELECT
    O.ORDER_ID,
    O.ORDER_NUMBER,
    O.ORDER_DATE,
    O.ORDER_STATUS,
    O.PAYMENT_STATUS,
    OI.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.BRAND,
    OI.QUANTITY,
    OI.UNIT_PRICE,
    OI.DISCOUNT_PERCENT,
    OI.LINE_TOTAL,
    O.TOTAL_AMOUNT,
    O.FINAL_AMOUNT,
    O.SHIPPING_ADDRESS,
    O.TRACKING_NUMBER,
    O.ESTIMATED_DELIVERY_DATE,
    O.ACTUAL_DELIVERY_DATE
FROM RETAILDB.ORDERS O
INNER JOIN RETAILDB.ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
INNER JOIN RETAILDB.PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE O.ORDER_STATUS NOT IN ('CANCELLED', 'REFUNDED');
