--liquibase formatted sql
--changeset RAML:aq345678901-4567-89ab-cdef-234567890123  runOnChange:true


CREATE OR REPLACE PROCEDURE ENERGYDB.SP_CALCULATE_ENERGY_BILL(
    CUSTOMER_ID_PARAM VARCHAR,
    BILLING_START_DATE DATE,
    BILLING_END_DATE DATE
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    RATE_PLAN_VAR VARCHAR(50);
    BASE_CHARGE_VAR DECIMAL(10,2);
    ENERGY_RATE DECIMAL(8,4);
    TOTAL_KWH DECIMAL(12,2);
    SOLAR_CREDIT_RATE DECIMAL(8,4);
    TOTAL_SOLAR_KWH DECIMAL(10,2);
    ENERGY_CHARGES DECIMAL(12,2);
    SOLAR_CREDITS DECIMAL(12,2);
    TOTAL_BILL DECIMAL(12,2);
    RESULT_MSG VARCHAR;
BEGIN
    -- Get customer rate plan
    SELECT RATE_PLAN INTO RATE_PLAN_VAR
    FROM ENERGYDB.CUSTOMERS
    WHERE CUSTOMER_ID = :CUSTOMER_ID_PARAM;

    IF (RATE_PLAN_VAR IS NULL) THEN
        RETURN 'ERROR: Customer not found: ' || :CUSTOMER_ID_PARAM;
    END IF;

    -- Get rate schedule
    SELECT BASE_CHARGE, ENERGY_CHARGE_PER_KWH, SOLAR_CREDIT_PER_KWH
    INTO BASE_CHARGE_VAR, ENERGY_RATE, SOLAR_CREDIT_RATE
    FROM ENERGYDB.RATE_SCHEDULES
    WHERE RATE_PLAN = :RATE_PLAN_VAR;

    -- Calculate consumption
    SELECT
        SUM(CR.CONSUMPTION_KWH),
        SUM(CR.GENERATED_SOLAR_KWH)
    INTO TOTAL_KWH, TOTAL_SOLAR_KWH
    FROM ENERGYDB.METERS M
    INNER JOIN ENERGYDB.CONSUMPTION_RECORDS CR ON M.METER_ID = CR.METER_ID
    WHERE M.CUSTOMER_ID = :CUSTOMER_ID_PARAM
    AND CR.READING_DATE BETWEEN :BILLING_START_DATE AND :BILLING_END_DATE;

    -- Calculate charges
    ENERGY_CHARGES := BASE_CHARGE_VAR + (COALESCE(TOTAL_KWH, 0) * ENERGY_RATE);
    SOLAR_CREDITS := COALESCE(TOTAL_SOLAR_KWH, 0) * SOLAR_CREDIT_RATE;
    TOTAL_BILL := ENERGY_CHARGES - SOLAR_CREDITS;

    RESULT_MSG := 'Bill calculated for customer ' || :CUSTOMER_ID_PARAM ||
                  '. Consumption: ' || COALESCE(TOTAL_KWH, 0) || ' kWh' ||
                  ', Solar Generation: ' || COALESCE(TOTAL_SOLAR_KWH, 0) || ' kWh' ||
                  ', Energy Charges: $' || ENERGY_CHARGES ||
                  ', Solar Credits: $' || SOLAR_CREDITS ||
                  ', Total Bill: $' || TOTAL_BILL;

    RETURN RESULT_MSG;
END;
$$;
