--liquibase formatted sql
--changeset RAML:ao123456789-2345-6789-abcd-012345678901  runOnChange:true


CREATE OR REPLACE VIEW ENERGYDATA.V_CUSTOMER_USAGE AS
SELECT
    C.CUSTOMER_ID,
    C.ACCOUNT_NUMBER,
    CASE
        WHEN C.ACCOUNT_TYPE = 'RESIDENTIAL' THEN C.FIRST_NAME || ' ' || C.LAST_NAME
        ELSE C.FIRST_NAME
    END AS CUSTOMER_NAME,
    C.SERVICE_ADDRESS,
    C.CITY,
    C.STATE,
    C.ACCOUNT_TYPE,
    C.RATE_PLAN,
    M.METER_NUMBER,
    M.METER_TYPE,
    SUM(CR.CONSUMPTION_KWH) AS TOTAL_CONSUMPTION_KWH,
    AVG(CR.CONSUMPTION_KWH) AS AVG_DAILY_CONSUMPTION_KWH,
    MAX(CR.PEAK_DEMAND_KW) AS MAX_PEAK_DEMAND_KW,
    SUM(CR.GENERATED_SOLAR_KWH) AS TOTAL_SOLAR_GENERATION_KWH,
    SUM(CR.NET_CONSUMPTION_KWH) AS NET_CONSUMPTION_KWH,
    COUNT(CR.CONSUMPTION_ID) AS READING_COUNT
FROM ENERGYDB.CUSTOMERS C
INNER JOIN ENERGYDB.METERS M ON C.CUSTOMER_ID = M.CUSTOMER_ID
LEFT JOIN ENERGYDB.CONSUMPTION_RECORDS CR ON M.METER_ID = CR.METER_ID
    AND CR.READING_DATE >= DATEADD(DAY, -30, CURRENT_DATE())
WHERE C.STATUS = 'ACTIVE'
GROUP BY
    C.CUSTOMER_ID, C.ACCOUNT_NUMBER, C.FIRST_NAME, C.LAST_NAME,
    C.SERVICE_ADDRESS, C.CITY, C.STATE, C.ACCOUNT_TYPE,
    C.RATE_PLAN, M.METER_NUMBER, M.METER_TYPE;
