--liquibase formatted sql
--changeset PratikL:ap234567890-3456-789a-bcde-123456789012  runOnChange:true


CREATE OR REPLACE VIEW ENERGYDATA.V_ENERGY_ANALYTICS AS
SELECT
    C.ACCOUNT_TYPE,
    C.RATE_PLAN,
    C.CITY,
    C.STATE,
    COUNT(DISTINCT C.CUSTOMER_ID) AS TOTAL_CUSTOMERS,
    SUM(CR.CONSUMPTION_KWH) AS TOTAL_CONSUMPTION_KWH,
    AVG(CR.CONSUMPTION_KWH) AS AVG_CONSUMPTION_PER_CUSTOMER,
    SUM(CR.GENERATED_SOLAR_KWH) AS TOTAL_SOLAR_GENERATION,
    AVG(CR.PEAK_DEMAND_KW) AS AVG_PEAK_DEMAND,
    AVG(CR.TEMPERATURE_F) AS AVG_TEMPERATURE,
    ROUND((SUM(CR.GENERATED_SOLAR_KWH) / NULLIF(SUM(CR.CONSUMPTION_KWH), 0)) * 100, 2) AS SOLAR_PENETRATION_PCT
FROM ENERGYDB.CUSTOMERS C
INNER JOIN ENERGYDB.METERS M ON C.CUSTOMER_ID = M.CUSTOMER_ID
LEFT JOIN ENERGYDB.CONSUMPTION_RECORDS CR ON M.METER_ID = CR.METER_ID
    AND CR.READING_DATE >= DATEADD(DAY, -30, CURRENT_DATE())
WHERE C.STATUS = 'ACTIVE'
GROUP BY
    C.ACCOUNT_TYPE, C.RATE_PLAN, C.CITY, C.STATE;
