--liquibase formatted sql
--changeset RAML:u123456789-ef01-2345-6789-012345678901  runOnChange:true


CREATE OR REPLACE VIEW LOGISTICSDATA.V_SHIPMENT_STATUS AS
SELECT
    S.SHIPMENT_ID,
    S.TRACKING_NUMBER,
    S.ORDER_ID,
    S.CARRIER,
    S.SERVICE_TYPE,
    S.STATUS,
    S.SHIP_DATE,
    S.ESTIMATED_DELIVERY_DATE,
    S.ACTUAL_DELIVERY_DATE,
    DATEDIFF(DAY, S.SHIP_DATE, COALESCE(S.ACTUAL_DELIVERY_DATE, CURRENT_TIMESTAMP())) AS DAYS_IN_TRANSIT,
    CASE
        WHEN S.ACTUAL_DELIVERY_DATE IS NOT NULL AND S.ACTUAL_DELIVERY_DATE <= S.ESTIMATED_DELIVERY_DATE THEN 'ON_TIME'
        WHEN S.ACTUAL_DELIVERY_DATE IS NOT NULL AND S.ACTUAL_DELIVERY_DATE > S.ESTIMATED_DELIVERY_DATE THEN 'DELAYED'
        WHEN CURRENT_TIMESTAMP() > S.ESTIMATED_DELIVERY_DATE AND S.STATUS NOT IN ('DELIVERED', 'RETURNED') THEN 'AT_RISK'
        ELSE 'ON_TRACK'
    END AS DELIVERY_PERFORMANCE,
    S.DESTINATION_ADDRESS,
    TE.EVENT_TIMESTAMP AS LAST_EVENT_TIME,
    TE.LOCATION AS LAST_KNOWN_LOCATION,
    TE.DESCRIPTION AS LAST_EVENT_DESCRIPTION
FROM LOGISTICSDB.SHIPMENTS S
LEFT JOIN (
    SELECT SHIPMENT_ID, EVENT_TIMESTAMP, LOCATION, DESCRIPTION
    FROM LOGISTICSDB.TRACKING_EVENTS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY SHIPMENT_ID ORDER BY EVENT_TIMESTAMP DESC) = 1
) TE ON S.SHIPMENT_ID = TE.SHIPMENT_ID;
