--liquibase formatted sql
--changeset PratikL:v234567890-f012-3456-789a-123456789012  runOnChange:true


CREATE OR REPLACE VIEW LOGISTICSDATA.V_WAREHOUSE_CAPACITY AS
SELECT
    W.WAREHOUSE_ID,
    W.WAREHOUSE_CODE,
    W.WAREHOUSE_NAME,
    W.CITY,
    W.STATE,
    W.CAPACITY_SQM,
    W.MANAGER_NAME,
    W.PHONE_NUMBER,
    COUNT(DISTINCT S.SHIPMENT_ID) AS ACTIVE_SHIPMENTS,
    SUM(S.PACKAGE_COUNT) AS TOTAL_PACKAGES
FROM LOGISTICSDB.WAREHOUSES W
LEFT JOIN LOGISTICSDB.SHIPMENTS S ON W.WAREHOUSE_CODE IN (
    SUBSTRING(S.ORIGIN_ADDRESS, 1, 100)
) AND S.STATUS IN ('PENDING', 'PROCESSING')
GROUP BY
    W.WAREHOUSE_ID,
    W.WAREHOUSE_CODE,
    W.WAREHOUSE_NAME,
    W.CITY,
    W.STATE,
    W.CAPACITY_SQM,
    W.MANAGER_NAME,
    W.PHONE_NUMBER;
