--liquibase formatted sql
--changeset PratikL:q789012345-abcd-ef01-2345-678901234567  runOnChange:true


CREATE OR REPLACE VIEW EDUDATA.V_COURSE_ENROLLMENT_STATUS AS
SELECT
    C.COURSE_ID,
    C.COURSE_CODE,
    C.COURSE_NAME,
    C.DEPARTMENT,
    C.CREDITS,
    C.SEMESTER,
    C.YEAR,
    C.MAX_ENROLLMENT,
    COUNT(E.ENROLLMENT_ID) AS CURRENT_ENROLLMENT,
    C.MAX_ENROLLMENT - COUNT(E.ENROLLMENT_ID) AS AVAILABLE_SEATS,
    ROUND((COUNT(E.ENROLLMENT_ID)::DECIMAL / C.MAX_ENROLLMENT) * 100, 2) AS FILL_PERCENTAGE,
    CASE
        WHEN COUNT(E.ENROLLMENT_ID) >= C.MAX_ENROLLMENT THEN 'FULL'
        WHEN COUNT(E.ENROLLMENT_ID) >= (C.MAX_ENROLLMENT * 0.9) THEN 'ALMOST_FULL'
        WHEN COUNT(E.ENROLLMENT_ID) >= (C.MAX_ENROLLMENT * 0.5) THEN 'AVAILABLE'
        ELSE 'OPEN'
    END AS ENROLLMENT_STATUS
FROM EDUDB.COURSES C
LEFT JOIN EDUDB.ENROLLMENTS E ON C.COURSE_ID = E.COURSE_ID AND E.STATUS = 'ENROLLED'
GROUP BY
    C.COURSE_ID,
    C.COURSE_CODE,
    C.COURSE_NAME,
    C.DEPARTMENT,
    C.CREDITS,
    C.SEMESTER,
    C.YEAR,
    C.MAX_ENROLLMENT;
