--liquibase formatted sql
--changeset RAML:p678901234-9abc-def0-1234-567890123456  runOnChange:true


CREATE OR REPLACE VIEW EDUDATA.V_STUDENT_TRANSCRIPT AS
SELECT
    S.STUDENT_ID,
    S.STUDENT_NUMBER,
    S.FIRST_NAME || ' ' || S.LAST_NAME AS STUDENT_NAME,
    S.PROGRAM,
    C.COURSE_CODE,
    C.COURSE_NAME,
    C.CREDITS,
    E.SEMESTER,
    E.YEAR,
    E.GRADE,
    E.GRADE_POINTS,
    E.TOTAL_SCORE,
    E.STATUS
FROM EDUDB.STUDENTS S
INNER JOIN EDUDB.ENROLLMENTS E ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN EDUDB.COURSES C ON E.COURSE_ID = C.COURSE_ID
WHERE E.STATUS = 'COMPLETED'
ORDER BY E.YEAR DESC, E.SEMESTER, C.COURSE_CODE;
