--liquibase formatted sql
--changeset RAML:h890123456-1234-5678-9abc-def012345678  runOnChange:true


CREATE OR REPLACE PROCEDURE HRDB.SP_APPROVE_LEAVE_REQUEST(
    LEAVE_REQUEST_ID_PARAM VARCHAR,
    APPROVER_ID_PARAM VARCHAR,
    APPROVAL_STATUS VARCHAR,
    NOTES VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    EMPLOYEE_ID_VAR VARCHAR;
    LEAVE_TYPE_VAR VARCHAR;
    DAYS_REQUESTED_VAR DECIMAL(4,1);
    RESULT_MSG VARCHAR;
BEGIN
    -- Get leave request details
    SELECT EMPLOYEE_ID, LEAVE_TYPE, DAYS_REQUESTED
    INTO EMPLOYEE_ID_VAR, LEAVE_TYPE_VAR, DAYS_REQUESTED_VAR
    FROM HRDB.LEAVE_REQUESTS
    WHERE LEAVE_REQUEST_ID = :LEAVE_REQUEST_ID_PARAM;

    -- Update leave request status
    UPDATE HRDB.LEAVE_REQUESTS
    SET STATUS = :APPROVAL_STATUS,
        APPROVER_ID = :APPROVER_ID_PARAM,
        APPROVAL_DATE = CURRENT_DATE(),
        APPROVAL_NOTES = :NOTES
    WHERE LEAVE_REQUEST_ID = :LEAVE_REQUEST_ID_PARAM;

    -- Build result message
    RESULT_MSG := 'Leave request ' || :LEAVE_REQUEST_ID_PARAM ||
                  ' for employee ' || :EMPLOYEE_ID_VAR ||
                  ' has been ' || :APPROVAL_STATUS ||
                  '. Type: ' || :LEAVE_TYPE_VAR ||
                  ', Days: ' || :DAYS_REQUESTED_VAR;

    RETURN RESULT_MSG;
END;
$$;
