--liquibase formatted sql
--changeset RAML:ab890123456-5678-9abc-def0-789012345678  runOnChange:true


CREATE OR REPLACE PROCEDURE REALESTATEDB.SP_SCHEDULE_SHOWING(
    PROPERTY_ID_PARAM VARCHAR,
    AGENT_ID_PARAM VARCHAR,
    CLIENT_NAME_PARAM VARCHAR,
    CLIENT_EMAIL_PARAM VARCHAR,
    CLIENT_PHONE_PARAM VARCHAR,
    SHOWING_DATETIME TIMESTAMP_NTZ,
    DURATION_MIN INT
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    SHOWING_ID_VAR VARCHAR;
    SHOWING_COUNT INT;
    PROPERTY_STATUS VARCHAR;
    RESULT_MSG VARCHAR;
BEGIN
    -- Check if property is available
    SELECT STATUS INTO PROPERTY_STATUS
    FROM REALESTATEDB.PROPERTIES
    WHERE PROPERTY_ID = :PROPERTY_ID_PARAM;

    IF (PROPERTY_STATUS IS NULL) THEN
        RETURN 'ERROR: Property not found: ' || :PROPERTY_ID_PARAM;
    END IF;

    IF (PROPERTY_STATUS NOT IN ('ACTIVE', 'UNDER_CONTRACT')) THEN
        RETURN 'ERROR: Property not available for showings. Status: ' || :PROPERTY_STATUS;
    END IF;

    -- Generate showing ID
    SELECT COUNT(*) + 1 INTO SHOWING_COUNT FROM REALESTATEDB.SHOWINGS;
    SHOWING_ID_VAR := 'SHOW' || LPAD(SHOWING_COUNT::VARCHAR, 3, '0');

    -- Insert showing
    INSERT INTO REALESTATEDB.SHOWINGS (
        SHOWING_ID,
        PROPERTY_ID,
        AGENT_ID,
        CLIENT_NAME,
        CLIENT_EMAIL,
        CLIENT_PHONE,
        SHOWING_DATE,
        DURATION_MINUTES,
        STATUS,
        FOLLOW_UP_REQUIRED
    ) VALUES (
        :SHOWING_ID_VAR,
        :PROPERTY_ID_PARAM,
        :AGENT_ID_PARAM,
        :CLIENT_NAME_PARAM,
        :CLIENT_EMAIL_PARAM,
        :CLIENT_PHONE_PARAM,
        :SHOWING_DATETIME,
        :DURATION_MIN,
        'SCHEDULED',
        FALSE
    );

    RESULT_MSG := 'Showing scheduled: ' || :SHOWING_ID_VAR ||
                  ' for property ' || :PROPERTY_ID_PARAM ||
                  ' on ' || TO_VARCHAR(:SHOWING_DATETIME, 'YYYY-MM-DD HH24:MI') ||
                  ' for client ' || :CLIENT_NAME_PARAM;

    RETURN RESULT_MSG;
END;
$$;
