--liquibase formatted sql
--changeset RAML:w345678901-0123-4567-89ab-234567890123  runOnChange:true


CREATE OR REPLACE PROCEDURE LOGISTICSDB.SP_UPDATE_SHIPMENT_STATUS(
    TRACKING_NUMBER_PARAM VARCHAR,
    NEW_STATUS VARCHAR,
    LOCATION_PARAM VARCHAR,
    DESCRIPTION_PARAM VARCHAR,
    SCANNED_BY_PARAM VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    SHIPMENT_ID_VAR VARCHAR;
    EVENT_ID_VAR VARCHAR;
    EVENT_COUNT INT;
    RESULT_MSG VARCHAR;
BEGIN
    -- Get shipment ID
    SELECT SHIPMENT_ID INTO SHIPMENT_ID_VAR
    FROM LOGISTICSDB.SHIPMENTS
    WHERE TRACKING_NUMBER = :TRACKING_NUMBER_PARAM;

    IF (SHIPMENT_ID_VAR IS NULL) THEN
        RETURN 'ERROR: Tracking number not found: ' || :TRACKING_NUMBER_PARAM;
    END IF;

    -- Generate event ID
    SELECT COUNT(*) + 1 INTO EVENT_COUNT FROM LOGISTICSDB.TRACKING_EVENTS;
    EVENT_ID_VAR := 'EVT' || LPAD(EVENT_COUNT::VARCHAR, 3, '0');

    -- Insert tracking event
    INSERT INTO LOGISTICSDB.TRACKING_EVENTS (
        EVENT_ID,
        SHIPMENT_ID,
        EVENT_TIMESTAMP,
        EVENT_TYPE,
        LOCATION,
        STATUS,
        DESCRIPTION,
        SCAN_BY
    ) VALUES (
        :EVENT_ID_VAR,
        :SHIPMENT_ID_VAR,
        CURRENT_TIMESTAMP(),
        :NEW_STATUS,
        :LOCATION_PARAM,
        :NEW_STATUS,
        :DESCRIPTION_PARAM,
        :SCANNED_BY_PARAM
    );

    -- Update shipment status
    UPDATE LOGISTICSDB.SHIPMENTS
    SET STATUS = :NEW_STATUS,
        ACTUAL_DELIVERY_DATE = CASE WHEN :NEW_STATUS = 'DELIVERED' THEN CURRENT_TIMESTAMP() ELSE ACTUAL_DELIVERY_DATE END
    WHERE SHIPMENT_ID = :SHIPMENT_ID_VAR;

    RESULT_MSG := 'Shipment ' || :TRACKING_NUMBER_PARAM ||
                  ' updated to status ' || :NEW_STATUS ||
                  ' at ' || :LOCATION_PARAM;

    RETURN RESULT_MSG;
END;
$$;
